import 'dart:ui';

import 'package:selection_dialogs/models/country.dart';
import 'package:selection_dialogs/models/language.dart';

final List<Country> countryList = [
  Country("Afghanistan", "AF", "assets/images/flags/afghanistan.png"),
  Country("Albania", "AL", "assets/images/flags/albania.png"),
  Country("Algeria", "DZ", "assets/images/flags/algeria.png"),
  Country("American Samoa", "AS", "assets/images/flags/american-samoa.png"),
  Country("Andorra", "AD", "assets/images/flags/andorra.png"),
  Country("Angola", "AO", "assets/images/flags/angola.png"),
  Country("Anguilla", "AI", "assets/images/flags/anguilla.png"),
  Country("Antigua and Barbuda", "AG", "assets/images/flags/antigua-and-barbuda.png"),
  Country("Argentina", "AR", "assets/images/flags/argentina.png"),
  Country("Armenia", "AM", "assets/images/flags/armenia.png"),
  Country("Aruba", "AW", "assets/images/flags/aruba.png"),
  Country("Australia", "AU", "assets/images/flags/australia.png"),
  Country("Austria", "AT", "assets/images/flags/austria.png"),
  Country("Azerbaijan", "AZ", "assets/images/flags/azerbaijan.png"),
  Country("Bahamas", "BS", "assets/images/flags/bahamas.png"),
  Country("Bahrain", "BH", "assets/images/flags/bahrain.png"),
  Country("Bangladesh", "BD", "assets/images/flags/bangladesh.png"),
  Country("Barbados", "BB", "assets/images/flags/barbados.png"),
  Country("Belarus", "BY", "assets/images/flags/belarus.png"),
  Country("Belgium", "BE", "assets/images/flags/belgium.png"),
  Country("Belize", "BZ", "assets/images/flags/belize.png"),
  Country("Benin", "BJ", "assets/images/flags/benin.png"),
  Country("Bermuda", "BM", "assets/images/flags/bermuda.png"),
  Country("Bhutan", "BT", "assets/images/flags/bhutan.png"),
  Country("Bolivia", "BO", "assets/images/flags/bolivia.png"),
  Country("Bosnia and Herzegovina", "BA", "assets/images/flags/bosnia-and-herzegovina.png"),
  Country("Botswana", "BW", "assets/images/flags/botswana.png"),
  Country("Brazil", "BR", "assets/images/flags/brazil.png"),
  Country("British Indian Ocean Territory", "IO", "assets/images/flags/british-indian-ocean-territory.png"),
  Country("Brunei", "BN", "assets/images/flags/brunei.png"),
  Country("Bulgaria", "BG", "assets/images/flags/bulgaria.png"),
  Country("Burkina Faso", "BF", "assets/images/flags/burkina-faso.png"),
  Country("Burundi", "BI", "assets/images/flags/burundi.png"),
  Country("Cambodia", "KH", "assets/images/flags/cambodia.png"),
  Country("Cameroon", "CM", "assets/images/flags/cameroon.png"),
  Country("Canada", "CA", "assets/images/flags/canada.png"),
  Country("Cape Verde", "CV", "assets/images/flags/cape-verde.png"),
  Country("Cayman Islands", "KY", "assets/images/flags/cayman-islands.png"),
  Country("Central African Republic", "CF", "assets/images/flags/central-african-republic.png"),
  Country("Chad", "TD", "assets/images/flags/chad.png"),
  Country("Chile", "CL", "assets/images/flags/chile.png"),
  Country("China", "CN", "assets/images/flags/china.png"),
  Country("Christmas Island", "CX", "assets/images/flags/christmas-island.png"),
  Country("Cocos Islands", "CC", "assets/images/flags/cocos-island.png"),
  Country("Colombia", "CO", "assets/images/flags/colombia.png"),
  Country("Comoros", "KM", "assets/images/flags/comoros.png"),
  Country("Republic of the Congo", "CG", "assets/images/flags/republic-of-the-congo.png"),
  Country("Democratic Republic of the Congo", "CD", "assets/images/flags/democratic-republic-of-congo.png"),
  Country("Cook Islands", "CK", "assets/images/flags/cook-islands.png"),
  Country("Costa Rica", "CR", "assets/images/flags/costa-rica.png"),
  Country("Ivory Coast", "CI", "assets/images/flags/ivory-coast.png"),
  Country("Croatia", "HR", "assets/images/flags/croatia.png"),
  Country("Cuba", "CU", "assets/images/flags/cuba.png"),
  Country("Cyprus", "CY", "assets/images/flags/cyprus.png"),
  Country("Czech Republic", "CZ", "assets/images/flags/czech-republic.png"),
  Country("Denmark", "DK", "assets/images/flags/denmark.png"),
  Country("Djibouti", "DJ", "assets/images/flags/djibouti.png"),
  Country("Dominica", "DM", "assets/images/flags/dominica.png"),
  Country("Dominican Republic", "DO", "assets/images/flags/dominican-republic.png"),
  Country("Ecuador", "EC", "assets/images/flags/ecuador.png"),
  Country("Egypt", "EG", "assets/images/flags/egypt.png"),
  Country("El Salvador", "SV", "assets/images/flags/salvador.png"),
  Country("Equatorial Guinea", "GQ", "assets/images/flags/equatorial-guinea.png"),
  Country("Eritrea", "ER", "assets/images/flags/eritrea.png"),
  Country("Estonia", "EE", "assets/images/flags/estonia.png"),
  Country("Ethiopia", "ET", "assets/images/flags/ethiopia.png"),
  Country("Falkland Islands", "FK", "assets/images/flags/falkland-islands.png"),
  Country("Faroe Islands", "FO", "assets/images/flags/faroe-islands.png"),
  Country("Fiji", "FJ", "assets/images/flags/fiji.png"),
  Country("Finland", "FI", "assets/images/flags/finland.png"),
  Country("France", "FR", "assets/images/flags/france.png"),
  // Country("French Guiana", "GF", "assets/images/flags/french-guiana.png"),
  Country("French Polynesia", "PF", "assets/images/flags/french-polynesia.png"),
  // Country("French Southern Territories", "TF", "assets/images/flags/french-southern-territories.png"),
  Country("Gabon", "GA", "assets/images/flags/gabon.png"),
  Country("Gambia", "GM", "assets/images/flags/gambia.png"),
  Country("Georgia", "GE", "assets/images/flags/georgia.png"),
  Country("Germany", "DE", "assets/images/flags/germany.png"),
  Country("Ghana", "GH", "assets/images/flags/ghana.png"),
  Country("Gibraltar", "GI", "assets/images/flags/gibraltar.png"),
  Country("Greece", "GR", "assets/images/flags/greece.png"),
  Country("Greenland", "GL", "assets/images/flags/greenland.png"),
  Country("Grenada", "GD", "assets/images/flags/grenada.png"),
  // Country("Guadeloupe", "GP", "assets/images/flags/guadeloupe.png"),
  Country("Guam", "GU", "assets/images/flags/guam.png"),
  Country("Guatemala", "GT", "assets/images/flags/guatemala.png"),
  Country("Guernsey", "GG", "assets/images/flags/guernsey.png"),
  Country("Guinea", "GN", "assets/images/flags/guinea.png"),
  Country("Guinea-Bissau", "GW", "assets/images/flags/guinea-bissau.png"),
  Country("Guyana", "GY", "assets/images/flags/guyana.png"),
  Country("Haiti", "HT", "assets/images/flags/haiti.png"),
  // Country("Heard Island and McDonald Islands", "HM", "assets/images/flags/heard-island-and-mcdonald-islands.png"),
  // Country("Holy See", "VA", "assets/images/flags/holy-see.png"),
  Country("Honduras", "HN", "assets/images/flags/honduras.png"),
  Country("Hong Kong", "HK", "assets/images/flags/hong-kong.png"),
  Country("Hungary", "HU", "assets/images/flags/hungary.png"),
  Country("Iceland", "IS", "assets/images/flags/iceland.png"),
  Country("India", "IN", "assets/images/flags/india.png"),
  Country("Indonesia", "ID", "assets/images/flags/indonesia.png"),
  Country("Iran", "IR", "assets/images/flags/iran.png"),
  Country("Iraq", "IQ", "assets/images/flags/iraq.png"),
  Country("Ireland", "IE", "assets/images/flags/ireland.png"),
  Country("Isle of Man", "IM", "assets/images/flags/isle-of-man.png"),
  Country("Israel", "IL", "assets/images/flags/israel.png"),
  Country("Italy", "IT", "assets/images/flags/italy.png"),
  Country("Jamaica", "JM", "assets/images/flags/jamaica.png"),
  Country("Japan", "JP", "assets/images/flags/japan.png"),
  Country("Jersey", "JE", "assets/images/flags/jersey.png"),
  Country("Jordan", "JO", "assets/images/flags/jordan.png"),
  Country("Kazakhstan", "KZ", "assets/images/flags/kazakhstan.png"),
  Country("Kenya", "KE", "assets/images/flags/kenya.png"),
  Country("Kiribati", "KI", "assets/images/flags/kiribati.png"),
  Country("North Korea", "KP", "assets/images/flags/north-korea.png"),
  Country("South Korea", "KR", "assets/images/flags/south-korea.png"),
  Country("Kuwait", "KW", "assets/images/flags/kuwait.png"),
  Country("Kyrgyzstan", "KG", "assets/images/flags/kyrgyzstan.png"),
  Country("Lao People's Democratic Republic", "LA", "assets/images/flags/laos.png"),
  Country("Latvia", "LV", "assets/images/flags/latvia.png"),
  Country("Lebanon", "LB", "assets/images/flags/lebanon.png"),
  Country("Lesotho", "LS", "assets/images/flags/lesotho.png"),
  Country("Liberia", "LR", "assets/images/flags/liberia.png"),
  Country("Libya", "LY", "assets/images/flags/libya.png"),
  Country("Liechtenstein", "LI", "assets/images/flags/liechtenstein.png"),
  Country("Lithuania", "LT", "assets/images/flags/lithuania.png"),
  Country("Luxembourg", "LU", "assets/images/flags/luxembourg.png"),
  Country("Macao", "MO", "assets/images/flags/macao.png"),
  // Country("Macedonia, the former Yugoslav Republic of", "MK", "assets/images/flags/macedonia,-the-former-yugoslav-republic-of.png"),
  Country("Madagascar", "MG", "assets/images/flags/madagascar.png"),
  Country("Malawi", "MW", "assets/images/flags/malawi.png"),
  Country("Malaysia", "MY", "assets/images/flags/malaysia.png"),
  Country("Maldives", "MV", "assets/images/flags/maldives.png"),
  Country("Mali", "ML", "assets/images/flags/mali.png"),
  Country("Malta", "MT", "assets/images/flags/malta.png"),
  Country("Marshall Islands", "MH", "assets/images/flags/marshall-island.png"),
  Country("Martinique", "MQ", "assets/images/flags/martinique.png"),
  Country("Mauritania", "MR", "assets/images/flags/mauritania.png"),
  Country("Mauritius", "MU", "assets/images/flags/mauritius.png"),
  // Country("Mayotte", "YT", "assets/images/flags/mayotte.png"),
  Country("Mexico", "MX", "assets/images/flags/mexico.png"),
  // Country("Micronesia, Federated States of", "FM", "assets/images/flags/micronesia,-federated-states-of.png"),
  Country("Moldova", "MD", "assets/images/flags/moldova.png"),
  Country("Monaco", "MC", "assets/images/flags/monaco.png"),
  Country("Mongolia", "MN", "assets/images/flags/mongolia.png"),
  Country("Montenegro", "ME", "assets/images/flags/montenegro.png"),
  Country("Montserrat", "MS", "assets/images/flags/montserrat.png"),
  Country("Morocco", "MA", "assets/images/flags/morocco.png"),
  Country("Mozambique", "MZ", "assets/images/flags/mozambique.png"),
  Country("Myanmar", "MM", "assets/images/flags/myanmar.png"),
  Country("Namibia", "NA", "assets/images/flags/namibia.png"),
  Country("Nauru", "NR", "assets/images/flags/nauru.png"),
  Country("Nepal", "NP", "assets/images/flags/nepal.png"),
  Country("Netherlands", "NL", "assets/images/flags/netherlands.png"),
  // Country("Netherlands Antilles", "AN", "assets/images/flags/netherlands-antilles.png"),
  // Country("New Caledonia", "NC", "assets/images/flags/new-caledonia.png"),
  Country("New Zealand", "NZ", "assets/images/flags/new-zealand.png"),
  Country("Nicaragua", "NI", "assets/images/flags/nicaragua.png"),
  Country("Niger", "NE", "assets/images/flags/niger.png"),
  Country("Nigeria", "NG", "assets/images/flags/nigeria.png"),
  Country("Niue", "NU", "assets/images/flags/niue.png"),
  Country("Norfolk Island", "NF", "assets/images/flags/norfolk-island.png"),
  Country("Northern Mariana Islands", "MP", "assets/images/flags/northern-marianas-islands.png"),
  Country("Norway", "NO", "assets/images/flags/norway.png"),
  Country("Oman", "OM", "assets/images/flags/oman.png"),
  Country("Pakistan", "PK", "assets/images/flags/pakistan.png"),
  Country("Palau", "PW", "assets/images/flags/palau.png"),
  Country("Palestine", "PS", "assets/images/flags/palestine.png"),
  Country("Panama", "PA", "assets/images/flags/panama.png"),
  Country("Papua New Guinea", "PG", "assets/images/flags/papua-new-guinea.png"),
  Country("Paraguay", "PY", "assets/images/flags/paraguay.png"),
  Country("Peru", "PE", "assets/images/flags/peru.png"),
  Country("Philippines", "PH", "assets/images/flags/philippines.png"),
  Country("Pitcairn", "PN", "assets/images/flags/pitcairn-islands.png"),
  Country("Poland", "PL", "assets/images/flags/poland.png"),
  Country("Portugal", "PT", "assets/images/flags/portugal.png"),
  Country("Puerto Rico", "PR", "assets/images/flags/puerto-rico.png"),
  Country("Qatar", "QA", "assets/images/flags/qatar.png"),
  // Country("Réunion", "RE", "assets/images/flags/réunion.png"),
  Country("Romania", "RO", "assets/images/flags/romania.png"),
  Country("Russia", "RU", "assets/images/flags/russia.png"),
  Country("Rwanda", "RW", "assets/images/flags/rwanda.png"),
  // Country("Saint Helena", "SH", "assets/images/flags/saint-helena.png"),
  Country("Saint Kitts and Nevis", "KN", "assets/images/flags/saint-kitts-and-nevis.png"),
  // Country("Saint Lucia", "LC", "assets/images/flags/saint-lucia.png"),
  // Country("Saint Pierre and Miquelon", "PM", "assets/images/flags/saint-pierre-and-miquelon.png"),
  // Country("Saint Vincent and the Grenadines", "VC", "assets/images/flags/saint-vincent-and-the-grenadines.png"),
  // Country("Saint Vincent & the Grenadines", "VC", "assets/images/flags/saint-vincent-&-the-grenadines.png"),
  // Country("St. Vincent and the Grenadines", "VC", "assets/images/flags/st.-vincent-and-the-grenadines.png"),
  Country("Samoa", "WS", "assets/images/flags/samoa.png"),
  Country("San Marino", "SM", "assets/images/flags/san-marino.png"),
  Country("Sao Tome and Principe", "ST", "assets/images/flags/sao-tome-and-principe.png"),
  Country("Saudi Arabia", "SA", "assets/images/flags/saudi-arabia.png"),
  Country("Senegal", "SN", "assets/images/flags/senegal.png"),
  Country("Serbia", "RS", "assets/images/flags/serbia.png"),
  Country("Seychelles", "SC", "assets/images/flags/seychelles.png"),
  Country("Sierra Leone", "SL", "assets/images/flags/sierra-leone.png"),
  Country("Singapore", "SG", "assets/images/flags/singapore.png"),
  Country("Slovakia", "SK", "assets/images/flags/slovakia.png"),
  Country("Slovenia", "SI", "assets/images/flags/slovenia.png"),
  Country("Solomon Islands", "SB", "assets/images/flags/solomon-islands.png"),
  Country("Somalia", "SO", "assets/images/flags/somalia.png"),
  Country("South Africa", "ZA", "assets/images/flags/south-africa.png"),
  // Country("South Georgia and the South Sandwich Islands", "GS", "assets/images/flags/south-georgia-and-the-south-sandwich-islands.png"),
  Country("South Sudan", "SS", "assets/images/flags/south-sudan.png"),
  Country("Spain", "ES", "assets/images/flags/spain.png"),
  Country("Sri Lanka", "LK", "assets/images/flags/sri-lanka.png"),
  Country("Sudan", "SD", "assets/images/flags/sudan.png"),
  Country("Suriname", "SR", "assets/images/flags/suriname.png"),
  // Country("Svalbard and Jan Mayen", "SJ", "assets/images/flags/svalbard-and-jan-mayen.png"),
  Country("Swaziland", "SZ", "assets/images/flags/swaziland.png"),
  Country("Sweden", "SE", "assets/images/flags/sweden.png"),
  Country("Switzerland", "CH", "assets/images/flags/switzerland.png"),
  Country("Syrian Arab Republic", "SY", "assets/images/flags/syria.png"),
  Country("Taiwan", "TW", "assets/images/flags/taiwan.png"),
  Country("Tajikistan", "TJ", "assets/images/flags/tajikistan.png"),
  Country("Tanzania, United Republic of", "TZ", "assets/images/flags/tanzania.png"),
  Country("Thailand", "TH", "assets/images/flags/thailand.png"),
  // Country("Timor-Leste", "TL", "assets/images/flags/timor-leste.png"),
  Country("Togo", "TG", "assets/images/flags/togo.png"),
  Country("Tokelau", "TK", "assets/images/flags/tokelau.png"),
  Country("Tonga", "TO", "assets/images/flags/tonga.png"),
  Country("Trinidad and Tobago", "TT", "assets/images/flags/trinidad-and-tobago.png"),
  Country("Tunisia", "TN", "assets/images/flags/tunisia.png"),
  Country("Turkey", "TR", "assets/images/flags/turkey.png"),
  Country("Turkmenistan", "TM", "assets/images/flags/turkmenistan.png"),
  Country("Turks and Caicos Islands", "TC", "assets/images/flags/turks-and-caicos.png"),
  Country("Tuvalu", "TV", "assets/images/flags/tuvalu.png"),
  Country("Uganda", "UG", "assets/images/flags/uganda.png"),
  Country("Ukraine", "UA", "assets/images/flags/ukraine.png"),
  Country("United Arab Emirates", "AE", "assets/images/flags/united-arab-emirates.png"),
  Country("United Kingdom", "GB", "assets/images/flags/united-kingdom.png"),
  Country("United States of America", "US", "assets/images/flags/united-states-of-america.png"),
  // Country("United States Minor Outlying Islands", "UM", "assets/images/flags/united-states-minor-outlying-islands.png"),
  Country("Uruguay", "UY", "assets/images/flags/uruguay.png"),
  Country("Uzbekistan", "UZ", "assets/images/flags/uzbekistan.png"),
  Country("Vanuatu", "VU", "assets/images/flags/vanuatu.png"),
  Country("Venezuela", "VE", "assets/images/flags/venezuela.png"),
  Country("Vietnam", "VN", "assets/images/flags/vietnam.png"),
  Country("Virgin Islands, British", "VG", "assets/images/flags/british-virgin-islands.png"),
  Country("Virgin Islands, U.S.", "VI", "assets/images/flags/virgin-islands.png"),
  Country("Western Sahara", "EH", "assets/images/flags/western-sahara.png"),
  Country("Yemen", "YE", "assets/images/flags/yemen.png"),
  Country("Zambia", "ZM", "assets/images/flags/zambia.png"),
  Country("Zimbabwe", "ZW", "assets/images/flags/zimbabwe.png"),
];

//BEFORE ADDING LANGUAGE ADD COUNTRY!!
Map<String, LanguageData> langData = {
  "Arabic": LanguageData(
    "Arabic",
    "العربية",
    const Locale('ar'),
    "assets/images/flags/saudi-arabia.png",
  ),
  "Bengali": LanguageData(
    "Bengali",
    "বাংলা",
    const Locale('bn'),
    "assets/images/flags/bangladesh.png",
  ),
  "Cantonese": LanguageData(
    "Cantonese",
    "廣東話",
    const Locale('zh', 'TW'),
    "assets/images/flags/hong-kong.png",
  ),
  "Czech": LanguageData(
    "Czech",
    "čeština ",
    const Locale('cs'),
    "assets/images/flags/czech-republic.png",
  ),
  "Dutch": LanguageData(
    "Dutch",
    "Nederlands",
    const Locale('nl'),
    "assets/images/flags/netherlands.png",
  ),
  "English": LanguageData(
    "English",
    "English (UK)",
    const Locale('en'),
    "assets/images/flags/united-kingdom.png",
  ),
  "French": LanguageData(
    "French",
    "Français",
    const Locale('fr'),
    "assets/images/flags/france.png",
  ),
  "German": LanguageData(
    "German",
    "Deutsch",
    const Locale('de'),
    "assets/images/flags/germany.png",
  ),
  "Greek": LanguageData(
    "Greek",
    "ελληνικά",
    const Locale('el'),
    "assets/images/flags/greece.png",
  ),
  "Hindi": LanguageData(
    "Hindi",
    "हिन्दी",
    const Locale('hi'),
    "assets/images/flags/india.png",
  ),
  "Indonesian": LanguageData(
    "Indonesian",
    "Bahasa Indonesia",
    const Locale('id'),
    "assets/images/flags/indonesia.png",
  ),
  "Italian": LanguageData(
    "Italian",
    "Italiano",
    const Locale('it'),
    "assets/images/flags/italy.png",
  ),
  "Japanese": LanguageData(
    "Japanese",
    "日本語",
    const Locale('ja'),
    "assets/images/flags/japan.png",
  ),
  "Korean": LanguageData(
    "Korean",
    "한국어",
    const Locale('ko'),
    "assets/images/flags/south-korea.png",
  ),
  "Mandarin": LanguageData(
    "Mandarin",
    "简体中文",
    const Locale('zh'),
    "assets/images/flags/china.png",
  ),
  "Norwegian": LanguageData(
    "Norwegian",
    "norsk",
    const Locale('no'),
    "assets/images/flags/norway.png",
  ),
  "Polish": LanguageData(
    "Polish",
    "Polski",
    const Locale('pl'),
    "assets/images/flags/poland.png",
  ),
  "Portuguese": LanguageData(
    "Portuguese",
    "Português",
    const Locale('pt'),
    "assets/images/flags/portugal.png",
  ),
  "Romanian": LanguageData(
    "Romanian",
    "român",
    const Locale('ro'),
    "assets/images/flags/romania.png",
  ),
  "Russian": LanguageData(
    "Russian",
    "Русский",
    const Locale('ru'),
    "assets/images/flags/russia.png",
  ),
  "Spanish": LanguageData(
    "Spanish",
    "Español",
    const Locale('es'),
    "assets/images/flags/spain.png",
  ),
  "Swedish": LanguageData(
    "Swedish",
    "Svenska",
    const Locale('sv'),
    "assets/images/flags/sweden.png",
  ),
  "Thai": LanguageData(
    "Thai",
    "ไทย",
    const Locale('th'),
    "assets/images/flags/thailand.png",
  ),
  "Turkish": LanguageData(
    "Turkish",
    "Türkçe",
    const Locale('tr'),
    "assets/images/flags/turkey.png",
  ),
  "Ukrainian": LanguageData(
    "Ukrainian",
    "Українська",
    const Locale('uk'),
    "assets/images/flags/ukraine.png",
  ),
};
